#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)
SKILLS_DIR="$ROOT_DIR/skills"

usage() {
  echo "Usage: $0 <skill-name> <skill-title> <normalized-spec-path> <source-requirement-path>" >&2
}

if [[ $# -ne 4 ]]; then
  usage
  exit 1
fi

SKILL_NAME="$1"
SKILL_TITLE="$2"
NORMALIZED_SPEC_PATH="$3"
SOURCE_REQUIREMENT_PATH="$4"
TARGET_DIR="$SKILLS_DIR/$SKILL_NAME"

if [[ ! "$SKILL_NAME" =~ ^[a-z0-9]+(-[a-z0-9]+)*$ ]]; then
  echo "Skill name must use kebab-case." >&2
  exit 1
fi

mkdir -p "$TARGET_DIR" "$TARGET_DIR/assets" "$TARGET_DIR/examples" "$TARGET_DIR/scripts"

cat > "$TARGET_DIR/SKILL.md" <<EOF
---
name: $SKILL_NAME
description: Generate a validated HTML weekly report for $SKILL_TITLE.
---

# $SKILL_TITLE

## 目的

在上游 \`create-report\` 已经产出并校验标准化 spec 后，
生成最终 HTML 周报。

## 输入

- normalized spec: $NORMALIZED_SPEC_PATH
- source requirement: $SOURCE_REQUIREMENT_PATH
- data files declared by the normalized spec

## 工作流

1. validate the normalized spec and input inventory
2. map input files to the declared data contracts
3. build each section in the validated order
4. generate conclusions using only declared metrics and evidence rules
5. render the final HTML report and include source-data notes

## 约束

- do not change the validated section order
- do not infer undeclared metric logic
- do not change the output format away from HTML
- do not explain changes without data evidence declared by the normalized spec

## 参考资料

- producer skill: $ROOT_DIR/skills/create-report
- spec contract: $ROOT_DIR/docs/skills/report-creator/spec.md
- operating model: $ROOT_DIR/docs/skills/report-creator/operating-model.md
EOF

cat > "$TARGET_DIR/README.md" <<EOF
# $SKILL_TITLE

Generated by \`create-report\` from:

- source requirement: $SOURCE_REQUIREMENT_PATH
- normalized spec: $NORMALIZED_SPEC_PATH

## 说明

This downstream skill produces an HTML weekly report using a validated spec and
declared data contracts.

## 目录结构

- \`SKILL.md\`: agent-facing report generation workflow
- \`skill.json\`: metadata
- \`assets/\`: HTML contract, outline, prompt, validation checklist
- \`examples/\`: spec and output examples
- \`scripts/\`: execution packaging placeholder
EOF

cat > "$TARGET_DIR/skill.json" <<EOF
{
  "name": "$SKILL_NAME",
  "title": "$SKILL_TITLE",
  "description": "Generate an HTML weekly report for $SKILL_TITLE from a validated spec.",
  "version": "0.1.0",
  "status": "draft",
  "visibility": "internal",
  "entry": "SKILL.md",
  "tags": ["reports", "weekly", "html", "generated"],
  "author": "raincai"
}
EOF

cat > "$TARGET_DIR/assets/html-contract.md" <<EOF
# HTML 合同

- title block
- period block
- stable section order
- charts and tables declared by the normalized spec
- conclusion blocks
- source-data notes
EOF

cat > "$TARGET_DIR/assets/report-outline.md" <<EOF
# 周报结构

Populate each report section from the normalized spec:
$NORMALIZED_SPEC_PATH

Required structure:

1. report header
2. period metadata
3. report body in validated section order
4. source-data notes
EOF

cat > "$TARGET_DIR/assets/report-prompt.md" <<EOF
# 周报生成 Prompt

Generate the HTML weekly report from the normalized spec and declared data
contracts only.

Rules:

- use only metrics and fields declared in the normalized spec
- keep the validated section order
- include charts, tables, and conclusion blocks where required
- block unsupported analysis instead of guessing
EOF

cat > "$TARGET_DIR/assets/validation-checklist.md" <<EOF
# 校验清单

- normalized spec exists
- required data contracts are mapped
- required sections are present
- output format is HTML
EOF

cat > "$TARGET_DIR/examples/normalized-spec.md" <<EOF
# 标准化 Spec 参考

$NORMALIZED_SPEC_PATH
EOF

cat > "$TARGET_DIR/examples/input_inventory.md" <<EOF
# 输入文件清单

Fill with the datasets required by the normalized spec.
EOF

cat > "$TARGET_DIR/examples/output-outline.html" <<EOF
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>$SKILL_TITLE</title>
  </head>
  <body>
    <header>
      <h1>$SKILL_TITLE</h1>
    </header>
    <main></main>
  </body>
</html>
EOF

cat > "$TARGET_DIR/scripts/README.md" <<EOF
# Scripts

Add execution scripts for the generated report here when the workflow moves from
documentation-only packaging to runnable packaging.
EOF

echo "Created or updated report skill: $SKILL_NAME"
